package com.interviewonline.ws

data class RealtimeEventRequest(
    val sessionId: String,
    val type: String,
    val code: String? = null,
    val codeSequence: Long? = null,
    val language: String? = null,
    val stepIndex: Int? = null,
    val rating: Int? = null,
    val notes: String? = null,
    val presenceStatus: String? = null,
    val lineNumber: Int? = null,
    val column: Int? = null,
    val selectionStartLineNumber: Int? = null,
    val selectionStartColumn: Int? = null,
    val selectionEndLineNumber: Int? = null,
    val selectionEndColumn: Int? = null,
    val cursorSequence: Long? = null,
    val key: String? = null,
    val keyCode: String? = null,
    val ctrlKey: Boolean? = null,
    val altKey: Boolean? = null,
    val shiftKey: Boolean? = null,
    val metaKey: Boolean? = null,
    val yjsUpdate: String? = null,
    val syncKey: String? = null,
    val yjsClientSequence: Long? = null,
    val yjsDocumentBase64: String? = null,
    /** Base64-encoded y-protocols awareness update (remote cursors / selections). */
    val awarenessUpdate: String? = null,
)
